#!/usr/bin/env python3
"""Render two-violation extension covers as chunked Lean source."""

from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path

from ramsey55 import (
    ExtensionBranch,
    ExtensionMultiplicityCertificate,
    ExtensionMultiplicityLeaf,
    Graph,
)

from generate_extension_multiplicity_certificates import (
    FORMAT,
    MULTIPLICITY,
    decode_certificate,
)


def render_witness(node: ExtensionMultiplicityLeaf, index: int) -> str:
    witness = node.witnesses[index]
    a, b, c, d = witness.vertices
    color = "true" if witness.color else "false"
    return f"{color} {a} {b} {c} {d}"


def render_cover(
    certificate: ExtensionMultiplicityCertificate, node_index: int
) -> str:
    node = certificate.nodes[node_index]
    if isinstance(node, ExtensionMultiplicityLeaf):
        return f"(.leaf {render_witness(node, 0)} {render_witness(node, 1)})"
    assert isinstance(node, ExtensionBranch)
    when_true = render_cover(certificate, node.true_child)
    when_false = render_cover(certificate, node.false_child)
    return f"(.branch {node.vertex} {when_true} {when_false})"


def render_graph(
    index: int,
    graph6: str,
    certificate: ExtensionMultiplicityCertificate,
) -> str:
    graph = Graph.from_graph6(graph6)
    rows = ",\n  ".join(str(row) for row in graph.adjacency)
    cover = render_cover(certificate, certificate.root)
    stem = f"reference42Two_{index:03d}"
    return f'''/-- Public representative {index}; source graph6: `{graph6}`. -/
def {stem}Rows : Array Nat := #[
  {rows}
]

def {stem}Base : RawColoring :=
  fun u v => Nat.testBit ({stem}Rows[u]!) v

def {stem}Cover : ExtensionCover2 :=
  {cover}

theorem {stem}_atLeastTwo :
    EveryExtensionCreatesAtLeastTwoMonochromatic5 42 {stem}Base :=
  checkExtensionCover2_sound (cover := {stem}Cover) (by decide +kernel)

def {stem}Certified : CertifiedTwoViolationGraph 42 where
  base := {stem}Base
  atLeastTwo := {stem}_atLeastTwo
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/reference/r55_42_extension_two_covers.json.gz"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("formal/Ramsey55/ExtensionMultiplicityCertificates"),
    )
    parser.add_argument("--batch-size", type=int, default=8)
    args = parser.parse_args()

    if args.batch_size <= 0:
        raise ValueError("batch size must be positive")
    with gzip.open(args.input, "rt", encoding="ascii") as compressed:
        document = json.load(compressed)
    if (
        document.get("format") != FORMAT
        or document.get("multiplicity") != MULTIPLICITY
    ):
        raise ValueError("unsupported multiplicity certificate input")
    records = document.get("records")
    if not isinstance(records, list) or len(records) != 328:
        raise ValueError("expected exactly 328 extension-cover records")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    batch_names: list[str] = []
    for batch_index, start in enumerate(range(0, len(records), args.batch_size)):
        batch_name = f"Batch{batch_index:02d}"
        batch_names.append(batch_name)
        body = [
            "/- This file is generated by",
            "tools/generate_lean_extension_multiplicity_certificates.py. -/",
            "import Ramsey55.Extension",
            "",
            "namespace Ramsey55",
            "",
        ]
        for index in range(start, min(start + args.batch_size, len(records))):
            record = records[index]
            certificate = decode_certificate(record["nodes"])
            body.append(render_graph(index, record["graph6"], certificate))
        body.extend(["end Ramsey55", ""])
        (args.output_dir / f"{batch_name}.lean").write_text(
            "\n".join(body), encoding="utf-8"
        )

    index_lines = [
        "/- This file is generated by",
        "tools/generate_lean_extension_multiplicity_certificates.py. -/",
        *(
            f"import Ramsey55.ExtensionMultiplicityCertificates.{name}"
            for name in batch_names
        ),
        "",
        "namespace Ramsey55",
        "",
        "/-- The 328 public representatives with checked two-violation",
        "extension theorems. -/",
        "def reference42TwoViolationCatalog :",
        "    List (CertifiedTwoViolationGraph 42) := [",
        *(
            f"  reference42Two_{index:03d}Certified{',' if index < 327 else ''}"
            for index in range(328)
        ),
        "]",
        "",
        "theorem reference42TwoViolationCatalog_length :",
        "    reference42TwoViolationCatalog.length = 328 := by",
        "  decide +kernel",
        "",
        "/-- Add all colour complements, giving 656 certified labelled graphs. -/",
        "def reference42TwoViolationCatalogWithComplements :",
        "    List (CertifiedTwoViolationGraph 42) :=",
        "  reference42TwoViolationCatalog ++",
        "    reference42TwoViolationCatalog.map (·.complement)",
        "",
        "theorem reference42TwoViolationCatalogWithComplements_length :",
        "    reference42TwoViolationCatalogWithComplements.length = 656 := by",
        "  decide +kernel",
        "",
        "theorem reference42TwoViolationCatalogWithComplements_all_atLeastTwo :",
        "    ∀ graph ∈ reference42TwoViolationCatalogWithComplements,",
        "      EveryExtensionCreatesAtLeastTwoMonochromatic5 42 graph.base := by",
        "  intro graph _",
        "  exact graph.atLeastTwo",
        "",
        "theorem reference42TwoViolationCatalogWithComplements_all_noExtension :",
        "    ∀ graph ∈ reference42TwoViolationCatalogWithComplements,",
        "      HasNoRamseyFreeOneVertexExtension 42 graph.base := by",
        "  intro graph _",
        "  exact graph.noExtension",
        "",
        "#print axioms",
        "  reference42TwoViolationCatalogWithComplements_all_atLeastTwo",
        "",
        "end Ramsey55",
        "",
    ]
    index_path = args.output_dir.parent / "ExtensionMultiplicityCertificates.lean"
    index_path.write_text("\n".join(index_lines), encoding="utf-8")
    print(f"wrote {len(batch_names)} Lean batches and {index_path}")


if __name__ == "__main__":
    main()
