#!/usr/bin/env python3
"""Render the checked extension-cover dataset as chunked Lean source."""

from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path

from ramsey55 import ExtensionBranch, ExtensionCertificate, ExtensionLeaf, Graph

from generate_extension_certificates import FORMAT, decode_certificate


def render_cover(certificate: ExtensionCertificate, node_index: int) -> str:
    node = certificate.nodes[node_index]
    if isinstance(node, ExtensionLeaf):
        a, b, c, d = node.vertices
        color = "true" if node.color else "false"
        return f"(.leaf {color} {a} {b} {c} {d})"
    assert isinstance(node, ExtensionBranch)
    when_true = render_cover(certificate, node.true_child)
    when_false = render_cover(certificate, node.false_child)
    return f"(.branch {node.vertex} {when_true} {when_false})"


def render_graph(index: int, graph6: str, certificate: ExtensionCertificate) -> str:
    graph = Graph.from_graph6(graph6)
    rows = ",\n  ".join(str(row) for row in graph.adjacency)
    cover = render_cover(certificate, certificate.root)
    stem = f"reference42_{index:03d}"
    return f'''/-- Public representative {index}; source graph6: `{graph6}`. -/
def {stem}Rows : Array Nat := #[
  {rows}
]

def {stem}Base : RawColoring :=
  fun u v => Nat.testBit ({stem}Rows[u]!) v

def {stem}Cover : ExtensionCover :=
  {cover}

theorem {stem}_noExtension :
    HasNoRamseyFreeOneVertexExtension 42 {stem}Base :=
  checkExtensionCover_sound (cover := {stem}Cover) (by decide +kernel)

def {stem}Certified : CertifiedNonextendableGraph 42 where
  base := {stem}Base
  noExtension := {stem}_noExtension
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/reference/r55_42_extension_covers.json.gz"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("formal/Ramsey55/ExtensionCertificates"),
    )
    parser.add_argument("--batch-size", type=int, default=16)
    args = parser.parse_args()

    if args.batch_size <= 0:
        raise ValueError("batch size must be positive")
    with gzip.open(args.input, "rt", encoding="ascii") as compressed:
        document = json.load(compressed)
    if document.get("format") != FORMAT:
        raise ValueError(f"unsupported input format: {document.get('format')!r}")
    records = document.get("records")
    if not isinstance(records, list) or len(records) != 328:
        raise ValueError("expected exactly 328 extension-cover records")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    batch_names: list[str] = []
    for batch_index, start in enumerate(range(0, len(records), args.batch_size)):
        batch_name = f"Batch{batch_index:02d}"
        batch_names.append(batch_name)
        body = [
            "/- This file is generated by tools/generate_lean_extension_certificates.py. -/",
            "import Ramsey55.Extension",
            "",
            "namespace Ramsey55",
            "",
        ]
        for index in range(start, min(start + args.batch_size, len(records))):
            record = records[index]
            graph6 = record["graph6"]
            certificate = decode_certificate(record["nodes"])
            body.append(render_graph(index, graph6, certificate))
        body.extend(["end Ramsey55", ""])
        (args.output_dir / f"{batch_name}.lean").write_text(
            "\n".join(body), encoding="utf-8"
        )

    index_lines = [
        "/- This file is generated by tools/generate_lean_extension_certificates.py. -/",
        *(f"import Ramsey55.ExtensionCertificates.{name}" for name in batch_names),
        "",
        "namespace Ramsey55",
        "",
        "/-- The 328 public representatives, each bundled with its kernel-checked",
        "one-vertex nonextension theorem. Their complements are certified by",
        "`CertifiedNonextendableGraph.complement`. -/",
        "def reference42Catalog : List (CertifiedNonextendableGraph 42) := [",
        *(
            f"  reference42_{index:03d}Certified{',' if index < 327 else ''}"
            for index in range(328)
        ),
        "]",
        "",
        "theorem reference42Catalog_length : reference42Catalog.length = 328 := by",
        "  decide +kernel",
        "",
        "theorem reference42Catalog_all_noExtension :",
        "    ∀ graph ∈ reference42Catalog,",
        "      HasNoRamseyFreeOneVertexExtension 42 graph.base := by",
        "  intro graph _",
        "  exact graph.noExtension",
        "",
        "/-- The 328 representatives and their 328 colour complements. -/",
        "def reference42CatalogWithComplements :",
        "    List (CertifiedNonextendableGraph 42) :=",
        "  reference42Catalog ++ reference42Catalog.map (·.complement)",
        "",
        "theorem reference42CatalogWithComplements_length :",
        "    reference42CatalogWithComplements.length = 656 := by",
        "  decide +kernel",
        "",
        "theorem reference42CatalogWithComplements_all_noExtension :",
        "    ∀ graph ∈ reference42CatalogWithComplements,",
        "      HasNoRamseyFreeOneVertexExtension 42 graph.base := by",
        "  intro graph _",
        "  exact graph.noExtension",
        "",
        "#print axioms reference42CatalogWithComplements_all_noExtension",
        "",
        "end Ramsey55",
        "",
    ]
    index_path = args.output_dir.parent / "ExtensionCertificates.lean"
    index_path.write_text("\n".join(index_lines), encoding="utf-8")

    print(f"wrote {len(batch_names)} Lean batches and {index_path}")


if __name__ == "__main__":
    main()
